### ISSUE TITLE
REST-API: Get a record file 's metadata result to 500 INTERNAL SERVER ERROR  if file not exists

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-records-resources#347]
Package version (if known): [v0.19.17](https://github.com/inveniosoftware/invenio-records-resources/commit/f1fb9a849d03af1d6ec4cddfc4e140a06788783b)

## Describe the bug
following the [docs](https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/#:~:text=a%20record%20file%27s-,metadata,-%C2%B6): 
Using Postman:
Providing wrong file name will results to internal server error
GET {{baseURL}}/api/records/{{record-id}}/files/{{unexisting-file-name}}

## Steps to Reproduce
1. Go to Postman
2. Send GET request: {{baseURL}}/api/records/{{record-id}}/files/{{unexisting-file-name}}
3. you get 500 error

## Expected behavior
quit gracefully with an error message

**Comment by Samk13** [comment]
Same error for [Download a record file](https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/#:~:text=filename%7D%22%0A%20%20%7D%0A%7D-,Download%20a%20record%20file,-%C2%B6):
{{baseURL}}/api/records/{{r-id}}/files/{{file-name}}/content

**Comment by ntarocco** [comment]
Do you have by any chance the stack trace?

**Comment by Samk13** [comment]
Get record meta data:

```console 
Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/invenio_records_resources/resources/files/resource.py", line 113, in read
    item = self.service.read_file_metadata(
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/invenio_records_resources/services/files/service.py", line 119, in read_file_metadata
    record.files[file_key],
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/invenio_records_resources/records/systemfields/files/manager.py", line 74, in inner
    return func(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/rdm-master-venv/lib/python3.9/site-packages/invenio_records_resources/records/systemfields/files/manager.py", line 316, in __getitem__
    raise KeyError(f'No file with key "{key}"')
KeyError: 'No file with key "278858583_362128319287101_3660395109940135677_n.jpg\n"'
```

**Comment by ntarocco** [comment]
Thanks!
Looks like that we are missing [here](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/files/service.py#L112) to check if the key exists and return `404` instead.
To be checked in the other resource's/service's methods too.

**Comment by Samk13** [comment]
Get group ID  that doesn't exists:

**GET {{baseURL}}/api/groups/{{group-id}}**

```console
Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_users_resources/resources/groups/resource.py", line 55, in read
    item = self.service.read(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_users_resources/services/groups/service.py", line 28, in read
    raise LookupError(f"No group with id '{id_}'.")
LookupError: No group with id '1'.
```

**Comment by Samk13** [comment]
I created a PR to fix get group and get avatar group routes that lead to 500 error
https://github.com/inveniosoftware/invenio-users-resources/pull/45
